site_name: Software Engineer Handbook
site_url: ''
site_description: "A comprehensive handbook for software engineers covering essential tools and technologies."
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Django: django.md
  - Pytest: pytest.md
  - Celery: celery.md
  - Redis: redis.md
  - RabbitMQ: rabbitmq.md
  - Poetry: poetry.md
  - PostgreSQL: postgresql.md
  - Docker: docker.md
  - CI/CD: ci_cd.md
  - Linux: linux.md
  - Git: git.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search